import machine


PIN_PWM = 16
PIN_FAN_ENABLE = 17
PIN_TACH = 22
PIN_ENC_CLK = 15
PIN_ENC_DT = 14
PIN_ENC_SW = 12
PIN_STATUS_LED = "LED"
LED_ARRAY = [ 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ]

PWM_FREQ_HZ = 25000
LED_PWM_FREQ_HZ = 1000
MIN_LED_BRIGHTNESS_PCT = 10

ENC_DEBOUNCE_US = 800
BTN_DEBOUNCE_MS = 30
BTN_DOUBLECLICK_MS = 350
BTN_AP_BOOT_HOLD_MS = 1500

DEFAULT_STEP = 2
DEFAULT_ENCODER_INVERT = True
DEFAULT_CURRENT_SPEED = 40
DEFAULT_PREDEFINED_SPEED = 40
DEFAULT_PREVIOUS_SPEED = 40
DEFAULT_BOOST_SPEED = 100
DEFAULT_MIN_SPEED = 20
DEFAULT_PWM_POLARITY = "high"
DEFAULT_TACH_PULSES_PER_REV = 2
DEFAULT_HOLD_THRESHOLD_MS = 1000
DEFAULT_DEVICE_NAME = "PicoFanController"
DEFAULT_FAN_ENABLED = False
DEFAULT_PREDEFINED_ACTIVE = False
DEFAULT_LED_BRIGHTNESS = 50
DEFAULT_LED_INVERT = False
DEFAULT_LED_CORRECTION_PCT = 100

LED_COUNT = len(LED_ARRAY)

AP_SSID_PREFIX = "PicoFanCtrl"
AP_IP = "192.168.4.1"

WIFI_CONNECT_TIMEOUT_S = 20
WIFI_CONNECT_RETRIES = 3

TACH_SAMPLE_WINDOW_MS = 1000

WEB_PORT = 80


def mac_suffix():
    mac = machine.unique_id()
    return "".join("{:02X}".format(b) for b in mac[-2:])
